name: On Tag

on:
  push:
    tags:
      - release-*

jobs:
  play:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cat (push)
        run: cat a.txt
