name: On Tag

on:
  push:
    branches:
      - master

jobs:
  play:
    needs: print
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cat (push)
        run: cat a.txt
