name: On Tag

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  play:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cat (push)
        run: cat a.txt
